### PR TITLE
Update CircleCI configs and add Slack Orb for notifications

### LINKED ISSUE #415: CircleCI config has to be updated to v2.1 to support Slack notifications (again)
## Short description

With the recent updates to the CircleCI web interface, activating the Slack Notifications is not as straightforward as before. You can set the webhook url in Circle CI's web interface and then have to add an Orb to the config:
image

In order to use the Orb, the config needs to be updated to version 2.1 - which requires some tweaks in addition to the Slack Orb.

### PR DESCRIPTION
**Pull request by keckelt**
Closes #415 

### Developer Checklist (Definition of Done)

* [ ] Descriptive title for this pull request provided (will be used for release notes later)
* [ ] All acceptance criteria from the issue are met
* [ ] Branch is up-to-date with the branch to be merged with, i.e., develop
* [ ] Code is cleaned up and formatted
* [ ] Code documentation written
* [ ] Unit tests written
* [ ] Build is successful
* [ ] [Summary of changes](#summary-of-changes) written
* [ ] Wiki documentation written
* [ ] Assign at least one reviewer
* [ ] Assign at least one assignee
* [ ] Add type label (e.g., *bug*, *enhancement*) to this pull request
* [ ] Add next version label (e.g., `release: minor`) to this PR following [semver](https://semver.org/)

### Summary of changes

* Update all CircleCI config templates to version 2.1
* Include the Slack Orb to let CircleCI send messages to Slack. This can no longer simply be done in the web interface (see #415)
* Predefined messages for successful and failed builds. Preview:
image

### CODE REVIEW

**Comment by keckelt** [comment]
I did not update the generator's own CircleCI Config: https://github.com/phovea/generator-phovea/blob/master/.circleci/config.yml

**Comment by anita-steiner** [comment]
@keckelt I'm not sure if we can define that as general workaround: not all customers have slack; so I would say that we update this in our configs where needed but it should not be part of the generator

**Comment by keckelt** [comment]
Makes sense, okay 👍

**Comment by thinkh** [comment]
In the meantime there is a new major version of the Slack Orb that works quite different from the previous one. I think we should upgrade to the newest version and not merge this PR.

https://circleci.com/blog/adding-iac-security-scans-to-ci-pipelines/

**Pull request closed without merging**
