### PR TITLE
Correct requirements in requirements.txt

### PR DESCRIPTION
**Pull request by oltionchampari**
Closes   phovea/generator-phovea#241

### Summary of changes
see phovea/generator-phovea#241

To test run `yo phovea:update` in a plugin in the master branch

### CODE REVIEW

**Comment by oltionchampari** [comment]
> Sorry, to pull that up again after that long time.
> 
> @oltionchampari Could you please provide a step-by-step example? Especially which repo I can use to test the `yo phovea:update` you mentioned? Because at the moment I do not know how to test this correctly. Thanks.

What this PR tries to solve is that when you execute` yo:phovea:update` inside a  `lib-slib` plugin and you select to add another known requirement through the prompt that already exists in your requirements.txt, then the generator will not merge them properly (there will be two entries in the requirements.txt with different versions).

The solution is rather naive, maybe a better solution would be to not allow the adding of a requirement that already exist in your plugin.
This bug occurs very rarely though, and you have to really be looking for it so maybe this PR is not necessary. I discovered it while trying to reproduce the bug that the connected issue describes.

**Comment by thinkh** [comment]
Ok, thanks for the clarification. I will give it a try.

**Comment by oltionchampari** [comment]
Changed implementation to remove the requirement from the `requirements.txt` if the same requirement is being added. Right now the requirements are being merged which causes the bug.

**Comment by oltionchampari** [comment]
Could it be that you had not pulled the latest changes? I tested again and i got the correct result:

```diff
- -e git+https://github.com/phovea/phovea_server.git@v2.2.0#egg=phovea_server
- -e git+https://github.com/datavisyn/tdp_core.git@v9.0.0#egg=tdp_core
+ phovea_server>=5.0.1,<6.0.0
+ -e git+https://github.com/datavisyn/tdp_core.git@v9.1.0#egg=tdp_core
```

I also attemted to write tests for this case  running yo `phovea-init-lib-slib` and then yo `phovea:update` on top but this does not work as it seems from [this](
https://github.com/yeoman/yeoman/issues/1531) issue.

**Comment by thinkh** [comment]
For @oltionchampari it works, because he selected tdp_core again in the last `yo phovea:update` step.

**Pull request merged**
